services:
  - type: web
    name: splitwise-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: USE_REAL_EMAILS
        value: "false"
      - key: MONGODB_URI
        value: mongodb+srv://kavishkhanna06_db_user:kavish123@cluster0.wv2snu3.mongodb.net/?appName=Cluster0
      - key: DATABASE_NAME
        value: splitwiseApp