services:
  - type: web
    name: backend-split-smart
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: USE_REAL_EMAILS
        value: "false"
      - key: MONGODB_URI
        value: mongodb+srv://kavishkhanna06_db_user:kavish123@cluster0.wv2snu3.mongodb.net/?appName=Cluster0
      - key: DATABASE_NAME
        value: splitwiseApp
      - key: FRONTEND_URL
        value: https://frontend-split-smart.vercel.app
      - key: GOOGLE_CALLBACK_URL
        value: https://backend-split-smart.onrender.com/auth/google/callback